### ISSUE TITLE
Squashed PRs aren't mirrored properly

### ISSUE THREAD

**Issue by steamp0rt** [steamp0rt/PRGlass#1]
What the title says

**Comment by steamp0rt** [comment]
Example: https://github.com/tgstation/tgstation/commit/72f5c3a831965b9af8c36c2eebc5542758d33c4a

**Comment by k-k-karma** [comment]
`# If it's a squash commit, you can't use -m 1, you need to remove it
# You also can't use -m 1 if it's a rebase and merge...`
from PRMirror's shell script @steamp0rt

**Comment by steamp0rt** [comment]
I fixed this reee
